name: PR

on:
  pull_request:
    paths-ignore:
      - 'ci/**'
      - '**/*.md'

env:
  IMAGE_NAME: docker-ecr-template

jobs:
  docker-build-and-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image
        run: docker build -t ${{ env.IMAGE_NAME }}:latest .
        working-directory: build

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Run tests
        run: |
          pip install -r requirements.txt
          # python -m pytest -v
  

  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install Black
        run: pip install black

      - name: Run black --check .
        id: check-formatting
        run: black --check .
        continue-on-error: true

      - name: If needed, commit black changes to the pull request
        if: ${{ steps.check-formatting.outcome == 'failure' }}
        run: |
          black .
          git config --global user.name ${{ secrets.CI_GITHUB_USERNAME }}
          git config --global user.email ${{ secrets.CI_GITHUB_EMAIL }}
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git checkout $GITHUB_HEAD_REF
          git commit -am "Fixup: Format Python code with Black"
          git push

